/* Auto-generated by frap_table_generator.py */
#pragma once

#include <stdint.h>

struct frap_cfg_entry {
    const char *name; /* task name / label */
    int resid;
    int spin_prio; /* numeric priority */
    int pid_hint; /* optional hint used by demo */
};

static const struct frap_cfg_entry frap_generated_table[] = {
    { "rb_0", 0, 89, 0 },
    { "rb_1", 0, 89, 1 },
    { "rb_2", 0, 89, 2 },
    { "rb_3", 0, 89, 3 },
    { "tlsf_0", 1, 119, 4 },
    { "tlsf_1", 1, 119, 5 },
    { "tlsf_2", 1, 119, 6 },
    { "tlsf_3", 1, 119, 7 },
    { "mat_0", 2, 179, 8 },
    { "mat_1", 2, 179, 9 },
    { "mat_2", 2, 179, 10 },
    { "mat_3", 2, 179, 11 },
    { "god_0", 0, 180, 12 },
    { "god_0", 1, 180, 12 },
    { "god_0", 2, 180, 12 },
    { "god_1", 0, 180, 13 },
    { "god_1", 1, 180, 13 },
    { "god_1", 2, 180, 13 },
    { "god_2", 0, 180, 14 },
    { "god_2", 1, 180, 14 },
    { "god_2", 2, 180, 14 },
    { "god_3", 0, 180, 15 },
    { "god_3", 1, 180, 15 },
    { "god_3", 2, 180, 15 },
};

static const int frap_generated_table_len = sizeof(frap_generated_table)/sizeof(frap_generated_table[0]);
